### ISSUE TITLE
Map disappears

### ISSUE THREAD

**Issue by jonathanhamel4** [rhinorust/MoMa#4]
Whenever we rotate the device or have an interaction that may refresh the page (i.e. entry or searchbar click on the page), the leaflet map disappears.

**Comment by jonathanhamel4** [comment]
We need to keep device on portrait mode

**Comment by jonathanhamel4** [comment]
Recently, I've been able to change from landscape to portrait without any map loss. Any changes? The issue seems to be solved..

**Comment by justin-yip** [comment]
The map disappears when I search for an artifact. After I added the POIs to the JSON, the map disappears once I search for an artifact without giving me an error. I'm guessing it's because the POIs in the JSON are different from the ones on the map. Therefore I'll try adding the POIs in the JSON to the map. If it still doesn't work I'll let you know.

**Comment by jonathanhamel4** [comment]
Is the map fully working now?

**Comment by RobRuff** [comment]
will start working on this issue now

**Comment by RobRuff** [comment]
Map only seems to disappear, when rotating device on Storylines page, or when performing an action such as scan QR, and going back to the storyline page.

**Comment by RobRuff** [comment]
Scoped out, team decided to only support portrait device orientation.
